name: Release

on:
  release:
    types:  [ created ]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  publishMavenCentral:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write

    environment:
      name: CD
      deployment: false

    steps:
      - name: Set environment for version
        uses: hfhbd/actions/setup-version@d782b0962c65733283de8488b55e37164a98c572 # main
        id: version
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Release maven artifacts
        run: ./gradlew publishToMavenCentral -Pversion=${{ steps.version.outputs.version }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PASSWORD }}
